version: "3"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    depends_on:
      - redis
    networks:
      - weather-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge

volumes:
  redis-data:
